-- =====================================================================
-- Clema Institutions Landing Pages — Canonical Schema
-- =====================================================================
-- Generated by pg_dump from the working landing.* schema, with FDW
-- setup prepended for cross-DB joins to ipeds + score_card.
--
-- To bootstrap a fresh local install:
--   createdb clema_landing
--   psql -d clema_landing -f db/setup_fdw.sql
--   psql -d clema_landing -f db/schema.sql
--
-- Or use the one-shot installer:
--   bash db/install.sh
-- =====================================================================


-- Dumped from database version 18.1 (Homebrew)
-- Dumped by pg_dump version 18.1 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: landing; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA landing;


SET default_table_access_method = heap;

--
-- Name: alembic_version; Type: TABLE; Schema: landing; Owner: -
--

CREATE TABLE landing.alembic_version (
    version_num character varying(32) NOT NULL
);


--
-- Name: brand_assets; Type: TABLE; Schema: landing; Owner: -
--

CREATE TABLE landing.brand_assets (
    unitid integer NOT NULL,
    logo_url text,
    logo_url_dark text,
    logo_icon_url text,
    colors_primary text,
    colors_secondary text,
    color_palette jsonb,
    fonts jsonb,
    source_url text,
    fetched_at timestamp with time zone DEFAULT now() NOT NULL,
    raw_payload_id bigint,
    parser_version text NOT NULL
);


--
-- Name: canonical_urls; Type: TABLE; Schema: landing; Owner: -
--

CREATE TABLE landing.canonical_urls (
    unitid integer NOT NULL,
    source_type text NOT NULL,
    url text NOT NULL,
    confidence numeric NOT NULL,
    llm_reasoning text,
    chosen_at timestamp with time zone DEFAULT now() NOT NULL,
    superseded_at timestamp with time zone
);


--
-- Name: cds_links; Type: TABLE; Schema: landing; Owner: -
--

CREATE TABLE landing.cds_links (
    id bigint NOT NULL,
    unitid integer NOT NULL,
    year smallint NOT NULL,
    cds_url text NOT NULL,
    is_pdf boolean,
    source_url text,
    fetched_at timestamp with time zone DEFAULT now() NOT NULL,
    raw_payload_id bigint,
    parser_version text NOT NULL
);


--
-- Name: cds_links_id_seq; Type: SEQUENCE; Schema: landing; Owner: -
--

CREATE SEQUENCE landing.cds_links_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: cds_links_id_seq; Type: SEQUENCE OWNED BY; Schema: landing; Owner: -
--

ALTER SEQUENCE landing.cds_links_id_seq OWNED BY landing.cds_links.id;


--
-- Name: crawl_log; Type: TABLE; Schema: landing; Owner: -
--

CREATE TABLE landing.crawl_log (
    id bigint NOT NULL,
    unitid integer NOT NULL,
    source_type text NOT NULL,
    url text NOT NULL,
    discovery_method text NOT NULL,
    relevance_score numeric,
    depth integer,
    discovered_at timestamp with time zone DEFAULT now() NOT NULL,
    run_id uuid NOT NULL
);


--
-- Name: crawl_log_id_seq; Type: SEQUENCE; Schema: landing; Owner: -
--

CREATE SEQUENCE landing.crawl_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: crawl_log_id_seq; Type: SEQUENCE OWNED BY; Schema: landing; Owner: -
--

ALTER SEQUENCE landing.crawl_log_id_seq OWNED BY landing.crawl_log.id;


--
-- Name: institutions; Type: TABLE; Schema: landing; Owner: -
--

CREATE TABLE landing.institutions (
    unitid integer NOT NULL,
    slug text NOT NULL,
    name text NOT NULL,
    city text,
    stabbr character(2) NOT NULL,
    state_name text,
    state_slug text NOT NULL,
    zip text,
    region text,
    fips_code integer,
    control_code integer,
    control_label text,
    control_slug text,
    sector_code integer,
    sector_label text,
    carnegie_basic_code integer,
    carnegie_basic_label text,
    carnegie_basic_slug text,
    is_hbcu boolean DEFAULT false NOT NULL,
    is_tribal boolean DEFAULT false NOT NULL,
    is_hospital boolean DEFAULT false NOT NULL,
    is_medical boolean DEFAULT false NOT NULL,
    is_landgrant boolean DEFAULT false NOT NULL,
    is_hsi boolean,
    opeid text,
    ein text,
    ueis text,
    webaddr_raw text,
    webaddr_normalized text,
    canonical_root_url text,
    domain text,
    registrable_domain text,
    robots_txt_url text,
    robots_txt_fetched_at timestamp with time zone,
    enabled boolean DEFAULT true NOT NULL,
    pilot_cohort boolean DEFAULT false NOT NULL,
    last_full_crawl_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: ir_contacts; Type: TABLE; Schema: landing; Owner: -
--

CREATE TABLE landing.ir_contacts (
    id bigint NOT NULL,
    unitid integer NOT NULL,
    name text NOT NULL,
    title text,
    email text,
    phone text,
    linkedin_url text,
    ordering smallint,
    source_url text,
    fetched_at timestamp with time zone DEFAULT now() NOT NULL,
    raw_payload_id bigint,
    parser_version text NOT NULL,
    confidence numeric
);


--
-- Name: ir_contacts_id_seq; Type: SEQUENCE; Schema: landing; Owner: -
--

CREATE SEQUENCE landing.ir_contacts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: ir_contacts_id_seq; Type: SEQUENCE OWNED BY; Schema: landing; Owner: -
--

ALTER SEQUENCE landing.ir_contacts_id_seq OWNED BY landing.ir_contacts.id;


--
-- Name: ir_documents; Type: TABLE; Schema: landing; Owner: -
--

CREATE TABLE landing.ir_documents (
    id bigint NOT NULL,
    unitid integer NOT NULL,
    doc_type text NOT NULL,
    title text,
    year smallint,
    doc_url text NOT NULL,
    mime_type text,
    page_count integer,
    storage_path text,
    extracted_text text,
    summary text,
    source_url text,
    fetched_at timestamp with time zone DEFAULT now() NOT NULL,
    raw_payload_id bigint,
    parser_version text NOT NULL,
    confidence numeric
);


--
-- Name: ir_documents_id_seq; Type: SEQUENCE; Schema: landing; Owner: -
--

CREATE SEQUENCE landing.ir_documents_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: ir_documents_id_seq; Type: SEQUENCE OWNED BY; Schema: landing; Owner: -
--

ALTER SEQUENCE landing.ir_documents_id_seq OWNED BY landing.ir_documents.id;


--
-- Name: ir_pages; Type: TABLE; Schema: landing; Owner: -
--

CREATE TABLE landing.ir_pages (
    unitid integer NOT NULL,
    office_name text,
    page_url text,
    page_summary text,
    parent_division text,
    source_url text,
    fetched_at timestamp with time zone DEFAULT now() NOT NULL,
    raw_payload_id bigint,
    parser_version text NOT NULL,
    confidence numeric
);


--
-- Name: job_postings; Type: TABLE; Schema: landing; Owner: -
--

CREATE TABLE landing.job_postings (
    id bigint NOT NULL,
    unitid integer NOT NULL,
    title text NOT NULL,
    department text,
    category text,
    posted_at date,
    expires_at date,
    apply_url text NOT NULL,
    source_board text,
    raw_description text,
    source_url text,
    fetched_at timestamp with time zone DEFAULT now() NOT NULL,
    raw_payload_id bigint,
    parser_version text NOT NULL
);


--
-- Name: job_postings_id_seq; Type: SEQUENCE; Schema: landing; Owner: -
--

CREATE SEQUENCE landing.job_postings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: job_postings_id_seq; Type: SEQUENCE OWNED BY; Schema: landing; Owner: -
--

ALTER SEQUENCE landing.job_postings_id_seq OWNED BY landing.job_postings.id;


--
-- Name: learned_patterns; Type: TABLE; Schema: landing; Owner: -
--

CREATE TABLE landing.learned_patterns (
    id bigint NOT NULL,
    unitid integer NOT NULL,
    source_type text NOT NULL,
    pattern_kind text NOT NULL,
    pattern_value text NOT NULL,
    confidence numeric,
    samples_seen integer DEFAULT 1,
    last_succeeded_at timestamp with time zone,
    last_failed_at timestamp with time zone
);


--
-- Name: learned_patterns_id_seq; Type: SEQUENCE; Schema: landing; Owner: -
--

CREATE SEQUENCE landing.learned_patterns_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: learned_patterns_id_seq; Type: SEQUENCE OWNED BY; Schema: landing; Owner: -
--

ALTER SEQUENCE landing.learned_patterns_id_seq OWNED BY landing.learned_patterns.id;


--
-- Name: research_awards; Type: TABLE; Schema: landing; Owner: -
--

CREATE TABLE landing.research_awards (
    id bigint NOT NULL,
    unitid integer NOT NULL,
    source_system text NOT NULL,
    external_id text NOT NULL,
    agency text,
    program_or_mechanism text,
    title text,
    pi_name text,
    pi_orcid text,
    amount_total_usd bigint,
    amount_obligated_usd bigint,
    fiscal_year smallint,
    start_date date,
    end_date date,
    abstract text,
    source_url text,
    fetched_at timestamp with time zone DEFAULT now() NOT NULL,
    raw_payload_id bigint,
    parser_version text NOT NULL
);


--
-- Name: mv_research_funding_summary; Type: MATERIALIZED VIEW; Schema: landing; Owner: -
--

CREATE MATERIALIZED VIEW landing.mv_research_funding_summary AS
 SELECT unitid,
    count(*) AS award_count_total,
    count(*) FILTER (WHERE (fiscal_year >= ((EXTRACT(year FROM CURRENT_DATE))::integer - 3))) AS award_count_last_3y,
    sum(amount_total_usd) AS amount_total_all_time_usd,
    sum(amount_total_usd) FILTER (WHERE (fiscal_year >= ((EXTRACT(year FROM CURRENT_DATE))::integer - 3))) AS amount_total_last_3y_usd,
    max(end_date) AS latest_award_end,
    count(*) FILTER (WHERE (source_system = 'nih_reporter'::text)) AS award_count_nih,
    count(*) FILTER (WHERE (source_system = 'nsf_awards'::text)) AS award_count_nsf,
    count(*) FILTER (WHERE (source_system = 'usaspending'::text)) AS award_count_usaspending,
    sum(amount_total_usd) FILTER (WHERE (source_system = 'nih_reporter'::text)) AS amount_nih_usd,
    sum(amount_total_usd) FILTER (WHERE (source_system = 'nsf_awards'::text)) AS amount_nsf_usd,
    sum(amount_total_usd) FILTER (WHERE (source_system = 'usaspending'::text)) AS amount_usaspending_usd
   FROM landing.research_awards
  GROUP BY unitid
  WITH NO DATA;


--
-- Name: notable_alumni; Type: TABLE; Schema: landing; Owner: -
--

CREATE TABLE landing.notable_alumni (
    id bigint NOT NULL,
    unitid integer NOT NULL,
    name text NOT NULL,
    field text,
    short_bio text,
    wikipedia_url text,
    source_url text,
    fetched_at timestamp with time zone DEFAULT now() NOT NULL,
    raw_payload_id bigint,
    parser_version text NOT NULL
);


--
-- Name: peer_groups; Type: TABLE; Schema: landing; Owner: -
--

CREATE TABLE landing.peer_groups (
    unitid integer NOT NULL,
    peer_unitid integer NOT NULL,
    rank smallint NOT NULL,
    similarity_score numeric,
    algorithm text NOT NULL,
    algorithm_version text NOT NULL,
    computed_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT peer_groups_check CHECK ((unitid <> peer_unitid))
);


--
-- Name: research_expenditures; Type: TABLE; Schema: landing; Owner: -
--

CREATE TABLE landing.research_expenditures (
    unitid integer NOT NULL,
    fiscal_year smallint NOT NULL,
    total_rd_expend_usd bigint,
    federal_rd_usd bigint,
    state_local_rd_usd bigint,
    institutional_rd_usd bigint,
    business_rd_usd bigint,
    nonprofit_rd_usd bigint,
    other_rd_usd bigint,
    by_field jsonb,
    rank_national integer,
    source_url text,
    fetched_at timestamp with time zone DEFAULT now() NOT NULL,
    raw_payload_id bigint,
    parser_version text NOT NULL
);


--
-- Name: wiki_summaries; Type: TABLE; Schema: landing; Owner: -
--

CREATE TABLE landing.wiki_summaries (
    unitid integer NOT NULL,
    wikipedia_url text,
    wikidata_qid text,
    short_description text,
    extract_summary text,
    founded_year integer,
    motto text,
    endowment_usd bigint,
    president_name text,
    thumbnail_url text,
    source_url text,
    fetched_at timestamp with time zone DEFAULT now() NOT NULL,
    raw_payload_id bigint,
    parser_version text NOT NULL
);


--
-- Name: mv_institution_page; Type: MATERIALIZED VIEW; Schema: landing; Owner: -
--

CREATE MATERIALIZED VIEW landing.mv_institution_page AS
 SELECT li.unitid,
    li.slug,
    li.name AS institution_name,
    li.city,
    li.stabbr,
    li.state_name,
    li.state_slug,
    li.region,
    li.zip,
    li.webaddr_normalized AS webaddr,
    li.canonical_root_url,
    li.domain,
    li.registrable_domain,
    li.opeid,
    li.ein,
    li.ueis,
    li.control_label,
    li.control_slug,
    li.sector_label,
    li.carnegie_basic_label,
    li.carnegie_basic_slug,
    li.is_hbcu,
    li.is_tribal,
    li.is_hospital,
    li.is_medical,
    li.is_landgrant,
    li.is_hsi,
    sc_latest.scorecard,
    ( SELECT to_jsonb(b.*) AS to_jsonb
           FROM landing.brand_assets b
          WHERE (b.unitid = li.unitid)) AS brand,
    ( SELECT to_jsonb(w.*) AS to_jsonb
           FROM landing.wiki_summaries w
          WHERE (w.unitid = li.unitid)) AS wiki,
    ( SELECT to_jsonb(irp.*) AS to_jsonb
           FROM landing.ir_pages irp
          WHERE (irp.unitid = li.unitid)) AS ir_page,
    ( SELECT to_jsonb(rfs.*) AS to_jsonb
           FROM landing.mv_research_funding_summary rfs
          WHERE (rfs.unitid = li.unitid)) AS research_summary,
    ( SELECT COALESCE(jsonb_agg(to_jsonb(ic.*) ORDER BY ic.ordering, ic.id), '[]'::jsonb) AS "coalesce"
           FROM landing.ir_contacts ic
          WHERE (ic.unitid = li.unitid)) AS ir_contacts,
    ( SELECT COALESCE(jsonb_agg(to_jsonb(d.*) ORDER BY d.year DESC NULLS LAST, d.id), '[]'::jsonb) AS "coalesce"
           FROM landing.ir_documents d
          WHERE (d.unitid = li.unitid)) AS documents,
    ( SELECT COALESCE(jsonb_agg(to_jsonb(cds.*) ORDER BY cds.year DESC, cds.id), '[]'::jsonb) AS "coalesce"
           FROM landing.cds_links cds
          WHERE (cds.unitid = li.unitid)) AS cds_links,
    ( SELECT COALESCE(jsonb_agg(to_jsonb(j.*) ORDER BY j.posted_at DESC NULLS LAST, j.id), '[]'::jsonb) AS "coalesce"
           FROM landing.job_postings j
          WHERE (j.unitid = li.unitid)) AS jobs,
    ( SELECT COALESCE(jsonb_agg(to_jsonb(na.*) ORDER BY na.id), '[]'::jsonb) AS "coalesce"
           FROM landing.notable_alumni na
          WHERE (na.unitid = li.unitid)) AS notable_alumni,
    ( SELECT COALESCE(jsonb_agg(to_jsonb(pg.*) ORDER BY pg.rank), '[]'::jsonb) AS "coalesce"
           FROM landing.peer_groups pg
          WHERE ((pg.unitid = li.unitid) AND (pg.algorithm = 'carnegie_state_control_v1'::text))) AS peers,
    ( SELECT COALESCE(jsonb_agg(to_jsonb(rx.*) ORDER BY rx.fiscal_year DESC), '[]'::jsonb) AS "coalesce"
           FROM landing.research_expenditures rx
          WHERE (rx.unitid = li.unitid)) AS research_expenditures,
    GREATEST(( SELECT brand_assets.fetched_at
           FROM landing.brand_assets
          WHERE (brand_assets.unitid = li.unitid)), ( SELECT wiki_summaries.fetched_at
           FROM landing.wiki_summaries
          WHERE (wiki_summaries.unitid = li.unitid)), ( SELECT ir_pages.fetched_at
           FROM landing.ir_pages
          WHERE (ir_pages.unitid = li.unitid))) AS landing_last_updated_at
   FROM (landing.institutions li
     LEFT JOIN LATERAL ( SELECT to_jsonb(sc.*) AS scorecard
           FROM score_card.fact_institution_yearly sc
          WHERE (sc.institution_id = li.unitid)
          ORDER BY sc.academic_year_id DESC
         LIMIT 1) sc_latest ON (true))
  WHERE li.enabled
  WITH NO DATA;


--
-- Name: notable_alumni_id_seq; Type: SEQUENCE; Schema: landing; Owner: -
--

CREATE SEQUENCE landing.notable_alumni_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: notable_alumni_id_seq; Type: SEQUENCE OWNED BY; Schema: landing; Owner: -
--

ALTER SEQUENCE landing.notable_alumni_id_seq OWNED BY landing.notable_alumni.id;


--
-- Name: raw_payloads; Type: TABLE; Schema: landing; Owner: -
--

CREATE TABLE landing.raw_payloads (
    id bigint NOT NULL,
    unitid integer NOT NULL,
    source_type text NOT NULL,
    url text NOT NULL,
    content_type text,
    http_status integer,
    body_text text,
    body_html text,
    body_blob_path text,
    body_sha256 character(64) NOT NULL,
    fetched_at timestamp with time zone DEFAULT now() NOT NULL,
    fetcher text NOT NULL,
    run_id uuid NOT NULL
);


--
-- Name: raw_payloads_id_seq; Type: SEQUENCE; Schema: landing; Owner: -
--

CREATE SEQUENCE landing.raw_payloads_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: raw_payloads_id_seq; Type: SEQUENCE OWNED BY; Schema: landing; Owner: -
--

ALTER SEQUENCE landing.raw_payloads_id_seq OWNED BY landing.raw_payloads.id;


--
-- Name: research_awards_id_seq; Type: SEQUENCE; Schema: landing; Owner: -
--

CREATE SEQUENCE landing.research_awards_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: research_awards_id_seq; Type: SEQUENCE OWNED BY; Schema: landing; Owner: -
--

ALTER SEQUENCE landing.research_awards_id_seq OWNED BY landing.research_awards.id;


--
-- Name: scraper_runs; Type: TABLE; Schema: landing; Owner: -
--

CREATE TABLE landing.scraper_runs (
    run_id uuid NOT NULL,
    unitid integer,
    source_type text,
    stage text NOT NULL,
    status text NOT NULL,
    started_at timestamp with time zone NOT NULL,
    finished_at timestamp with time zone,
    duration_ms integer,
    error_class text,
    error_message text,
    rows_written integer,
    llm_tokens_in integer,
    llm_tokens_out integer,
    cost_usd numeric(10,5)
);


--
-- Name: sitemap_entries; Type: TABLE; Schema: landing; Owner: -
--

CREATE TABLE landing.sitemap_entries (
    id bigint NOT NULL,
    sitemap_id bigint NOT NULL,
    unitid integer NOT NULL,
    url text NOT NULL,
    lastmod timestamp with time zone,
    changefreq text,
    priority numeric,
    classified_as text,
    classification_confidence numeric
);


--
-- Name: sitemap_entries_id_seq; Type: SEQUENCE; Schema: landing; Owner: -
--

CREATE SEQUENCE landing.sitemap_entries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: sitemap_entries_id_seq; Type: SEQUENCE OWNED BY; Schema: landing; Owner: -
--

ALTER SEQUENCE landing.sitemap_entries_id_seq OWNED BY landing.sitemap_entries.id;


--
-- Name: sitemaps; Type: TABLE; Schema: landing; Owner: -
--

CREATE TABLE landing.sitemaps (
    id bigint NOT NULL,
    unitid integer NOT NULL,
    sitemap_url text NOT NULL,
    sitemap_type text,
    fetched_at timestamp with time zone DEFAULT now() NOT NULL,
    entry_count integer,
    http_status integer
);


--
-- Name: sitemaps_id_seq; Type: SEQUENCE; Schema: landing; Owner: -
--

CREATE SEQUENCE landing.sitemaps_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: sitemaps_id_seq; Type: SEQUENCE OWNED BY; Schema: landing; Owner: -
--

ALTER SEQUENCE landing.sitemaps_id_seq OWNED BY landing.sitemaps.id;


--
-- Name: source_types; Type: TABLE; Schema: landing; Owner: -
--

CREATE TABLE landing.source_types (
    source_type text NOT NULL,
    description text NOT NULL,
    default_queue text NOT NULL,
    refresh_cadence_days integer,
    is_active boolean DEFAULT true NOT NULL
);


--
-- Name: v_carnegie_counts; Type: VIEW; Schema: landing; Owner: -
--

CREATE VIEW landing.v_carnegie_counts AS
 SELECT carnegie_basic_slug,
    carnegie_basic_code,
    carnegie_basic_label,
    count(*) AS institution_count
   FROM landing.institutions
  WHERE (enabled AND (carnegie_basic_slug IS NOT NULL))
  GROUP BY carnegie_basic_slug, carnegie_basic_code, carnegie_basic_label;


--
-- Name: v_state_counts; Type: VIEW; Schema: landing; Owner: -
--

CREATE VIEW landing.v_state_counts AS
 SELECT state_slug,
    stabbr,
    state_name,
    region,
    count(*) AS institution_count,
    sum(
        CASE
            WHEN is_hbcu THEN 1
            ELSE 0
        END) AS hbcu_count,
    sum(
        CASE
            WHEN is_tribal THEN 1
            ELSE 0
        END) AS tribal_count
   FROM landing.institutions
  WHERE enabled
  GROUP BY state_slug, stabbr, state_name, region;


--
-- Name: cds_links id; Type: DEFAULT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.cds_links ALTER COLUMN id SET DEFAULT nextval('landing.cds_links_id_seq'::regclass);


--
-- Name: crawl_log id; Type: DEFAULT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.crawl_log ALTER COLUMN id SET DEFAULT nextval('landing.crawl_log_id_seq'::regclass);


--
-- Name: ir_contacts id; Type: DEFAULT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.ir_contacts ALTER COLUMN id SET DEFAULT nextval('landing.ir_contacts_id_seq'::regclass);


--
-- Name: ir_documents id; Type: DEFAULT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.ir_documents ALTER COLUMN id SET DEFAULT nextval('landing.ir_documents_id_seq'::regclass);


--
-- Name: job_postings id; Type: DEFAULT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.job_postings ALTER COLUMN id SET DEFAULT nextval('landing.job_postings_id_seq'::regclass);


--
-- Name: learned_patterns id; Type: DEFAULT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.learned_patterns ALTER COLUMN id SET DEFAULT nextval('landing.learned_patterns_id_seq'::regclass);


--
-- Name: notable_alumni id; Type: DEFAULT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.notable_alumni ALTER COLUMN id SET DEFAULT nextval('landing.notable_alumni_id_seq'::regclass);


--
-- Name: raw_payloads id; Type: DEFAULT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.raw_payloads ALTER COLUMN id SET DEFAULT nextval('landing.raw_payloads_id_seq'::regclass);


--
-- Name: research_awards id; Type: DEFAULT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.research_awards ALTER COLUMN id SET DEFAULT nextval('landing.research_awards_id_seq'::regclass);


--
-- Name: sitemap_entries id; Type: DEFAULT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.sitemap_entries ALTER COLUMN id SET DEFAULT nextval('landing.sitemap_entries_id_seq'::regclass);


--
-- Name: sitemaps id; Type: DEFAULT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.sitemaps ALTER COLUMN id SET DEFAULT nextval('landing.sitemaps_id_seq'::regclass);


--
-- Name: alembic_version alembic_version_pkc; Type: CONSTRAINT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.alembic_version
    ADD CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num);


--
-- Name: brand_assets brand_assets_pkey; Type: CONSTRAINT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.brand_assets
    ADD CONSTRAINT brand_assets_pkey PRIMARY KEY (unitid);


--
-- Name: canonical_urls canonical_urls_pkey; Type: CONSTRAINT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.canonical_urls
    ADD CONSTRAINT canonical_urls_pkey PRIMARY KEY (unitid, source_type, chosen_at);


--
-- Name: cds_links cds_links_pkey; Type: CONSTRAINT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.cds_links
    ADD CONSTRAINT cds_links_pkey PRIMARY KEY (id);


--
-- Name: cds_links cds_links_unitid_year_key; Type: CONSTRAINT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.cds_links
    ADD CONSTRAINT cds_links_unitid_year_key UNIQUE (unitid, year);


--
-- Name: crawl_log crawl_log_pkey; Type: CONSTRAINT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.crawl_log
    ADD CONSTRAINT crawl_log_pkey PRIMARY KEY (id);


--
-- Name: crawl_log crawl_log_unitid_source_type_url_run_id_key; Type: CONSTRAINT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.crawl_log
    ADD CONSTRAINT crawl_log_unitid_source_type_url_run_id_key UNIQUE (unitid, source_type, url, run_id);


--
-- Name: institutions institutions_pkey; Type: CONSTRAINT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.institutions
    ADD CONSTRAINT institutions_pkey PRIMARY KEY (unitid);


--
-- Name: institutions institutions_slug_key; Type: CONSTRAINT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.institutions
    ADD CONSTRAINT institutions_slug_key UNIQUE (slug);


--
-- Name: ir_contacts ir_contacts_pkey; Type: CONSTRAINT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.ir_contacts
    ADD CONSTRAINT ir_contacts_pkey PRIMARY KEY (id);


--
-- Name: ir_contacts ir_contacts_unitid_name_title_key; Type: CONSTRAINT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.ir_contacts
    ADD CONSTRAINT ir_contacts_unitid_name_title_key UNIQUE (unitid, name, title);


--
-- Name: ir_documents ir_documents_pkey; Type: CONSTRAINT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.ir_documents
    ADD CONSTRAINT ir_documents_pkey PRIMARY KEY (id);


--
-- Name: ir_documents ir_documents_unitid_doc_type_year_doc_url_key; Type: CONSTRAINT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.ir_documents
    ADD CONSTRAINT ir_documents_unitid_doc_type_year_doc_url_key UNIQUE (unitid, doc_type, year, doc_url);


--
-- Name: ir_pages ir_pages_pkey; Type: CONSTRAINT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.ir_pages
    ADD CONSTRAINT ir_pages_pkey PRIMARY KEY (unitid);


--
-- Name: job_postings job_postings_pkey; Type: CONSTRAINT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.job_postings
    ADD CONSTRAINT job_postings_pkey PRIMARY KEY (id);


--
-- Name: job_postings job_postings_unitid_apply_url_key; Type: CONSTRAINT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.job_postings
    ADD CONSTRAINT job_postings_unitid_apply_url_key UNIQUE (unitid, apply_url);


--
-- Name: learned_patterns learned_patterns_pkey; Type: CONSTRAINT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.learned_patterns
    ADD CONSTRAINT learned_patterns_pkey PRIMARY KEY (id);


--
-- Name: learned_patterns learned_patterns_unitid_source_type_pattern_kind_pattern_va_key; Type: CONSTRAINT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.learned_patterns
    ADD CONSTRAINT learned_patterns_unitid_source_type_pattern_kind_pattern_va_key UNIQUE (unitid, source_type, pattern_kind, pattern_value);


--
-- Name: notable_alumni notable_alumni_pkey; Type: CONSTRAINT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.notable_alumni
    ADD CONSTRAINT notable_alumni_pkey PRIMARY KEY (id);


--
-- Name: notable_alumni notable_alumni_unitid_name_key; Type: CONSTRAINT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.notable_alumni
    ADD CONSTRAINT notable_alumni_unitid_name_key UNIQUE (unitid, name);


--
-- Name: peer_groups peer_groups_pkey; Type: CONSTRAINT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.peer_groups
    ADD CONSTRAINT peer_groups_pkey PRIMARY KEY (unitid, algorithm, algorithm_version, peer_unitid);


--
-- Name: raw_payloads raw_payloads_pkey; Type: CONSTRAINT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.raw_payloads
    ADD CONSTRAINT raw_payloads_pkey PRIMARY KEY (id);


--
-- Name: research_awards research_awards_pkey; Type: CONSTRAINT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.research_awards
    ADD CONSTRAINT research_awards_pkey PRIMARY KEY (id);


--
-- Name: research_awards research_awards_source_system_external_id_key; Type: CONSTRAINT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.research_awards
    ADD CONSTRAINT research_awards_source_system_external_id_key UNIQUE (source_system, external_id);


--
-- Name: research_expenditures research_expenditures_pkey; Type: CONSTRAINT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.research_expenditures
    ADD CONSTRAINT research_expenditures_pkey PRIMARY KEY (unitid, fiscal_year);


--
-- Name: scraper_runs scraper_runs_pkey; Type: CONSTRAINT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.scraper_runs
    ADD CONSTRAINT scraper_runs_pkey PRIMARY KEY (run_id);


--
-- Name: sitemap_entries sitemap_entries_pkey; Type: CONSTRAINT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.sitemap_entries
    ADD CONSTRAINT sitemap_entries_pkey PRIMARY KEY (id);


--
-- Name: sitemap_entries sitemap_entries_sitemap_id_url_key; Type: CONSTRAINT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.sitemap_entries
    ADD CONSTRAINT sitemap_entries_sitemap_id_url_key UNIQUE (sitemap_id, url);


--
-- Name: sitemaps sitemaps_pkey; Type: CONSTRAINT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.sitemaps
    ADD CONSTRAINT sitemaps_pkey PRIMARY KEY (id);


--
-- Name: sitemaps sitemaps_unitid_sitemap_url_key; Type: CONSTRAINT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.sitemaps
    ADD CONSTRAINT sitemaps_unitid_sitemap_url_key UNIQUE (unitid, sitemap_url);


--
-- Name: source_types source_types_pkey; Type: CONSTRAINT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.source_types
    ADD CONSTRAINT source_types_pkey PRIMARY KEY (source_type);


--
-- Name: wiki_summaries wiki_summaries_pkey; Type: CONSTRAINT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.wiki_summaries
    ADD CONSTRAINT wiki_summaries_pkey PRIMARY KEY (unitid);


--
-- Name: ix_alumni_inst; Type: INDEX; Schema: landing; Owner: -
--

CREATE INDEX ix_alumni_inst ON landing.notable_alumni USING btree (unitid);


--
-- Name: ix_canon_current; Type: INDEX; Schema: landing; Owner: -
--

CREATE INDEX ix_canon_current ON landing.canonical_urls USING btree (unitid, source_type) WHERE (superseded_at IS NULL);


--
-- Name: ix_cds_inst; Type: INDEX; Schema: landing; Owner: -
--

CREATE INDEX ix_cds_inst ON landing.cds_links USING btree (unitid, year DESC);


--
-- Name: ix_crawl_log_inst_src; Type: INDEX; Schema: landing; Owner: -
--

CREATE INDEX ix_crawl_log_inst_src ON landing.crawl_log USING btree (unitid, source_type);


--
-- Name: ix_ircontacts_email; Type: INDEX; Schema: landing; Owner: -
--

CREATE INDEX ix_ircontacts_email ON landing.ir_contacts USING btree (email) WHERE (email IS NOT NULL);


--
-- Name: ix_ircontacts_inst; Type: INDEX; Schema: landing; Owner: -
--

CREATE INDEX ix_ircontacts_inst ON landing.ir_contacts USING btree (unitid);


--
-- Name: ix_irdocs_inst_type; Type: INDEX; Schema: landing; Owner: -
--

CREATE INDEX ix_irdocs_inst_type ON landing.ir_documents USING btree (unitid, doc_type, year DESC);


--
-- Name: ix_jobs_inst_cat; Type: INDEX; Schema: landing; Owner: -
--

CREATE INDEX ix_jobs_inst_cat ON landing.job_postings USING btree (unitid, category, posted_at DESC);


--
-- Name: ix_landing_inst_carnegie; Type: INDEX; Schema: landing; Owner: -
--

CREATE INDEX ix_landing_inst_carnegie ON landing.institutions USING btree (carnegie_basic_code);


--
-- Name: ix_landing_inst_carnegie_slug; Type: INDEX; Schema: landing; Owner: -
--

CREATE INDEX ix_landing_inst_carnegie_slug ON landing.institutions USING btree (carnegie_basic_slug);


--
-- Name: ix_landing_inst_control; Type: INDEX; Schema: landing; Owner: -
--

CREATE INDEX ix_landing_inst_control ON landing.institutions USING btree (control_code);


--
-- Name: ix_landing_inst_domain; Type: INDEX; Schema: landing; Owner: -
--

CREATE INDEX ix_landing_inst_domain ON landing.institutions USING btree (registrable_domain);


--
-- Name: ix_landing_inst_hbcu; Type: INDEX; Schema: landing; Owner: -
--

CREATE INDEX ix_landing_inst_hbcu ON landing.institutions USING btree (is_hbcu) WHERE is_hbcu;


--
-- Name: ix_landing_inst_hsi; Type: INDEX; Schema: landing; Owner: -
--

CREATE INDEX ix_landing_inst_hsi ON landing.institutions USING btree (is_hsi) WHERE is_hsi;


--
-- Name: ix_landing_inst_pilot; Type: INDEX; Schema: landing; Owner: -
--

CREATE INDEX ix_landing_inst_pilot ON landing.institutions USING btree (pilot_cohort) WHERE pilot_cohort;


--
-- Name: ix_landing_inst_region; Type: INDEX; Schema: landing; Owner: -
--

CREATE INDEX ix_landing_inst_region ON landing.institutions USING btree (region);


--
-- Name: ix_landing_inst_slug; Type: INDEX; Schema: landing; Owner: -
--

CREATE INDEX ix_landing_inst_slug ON landing.institutions USING btree (slug);


--
-- Name: ix_landing_inst_state; Type: INDEX; Schema: landing; Owner: -
--

CREATE INDEX ix_landing_inst_state ON landing.institutions USING btree (stabbr);


--
-- Name: ix_landing_inst_state_slug; Type: INDEX; Schema: landing; Owner: -
--

CREATE INDEX ix_landing_inst_state_slug ON landing.institutions USING btree (state_slug);


--
-- Name: ix_landing_inst_tribal; Type: INDEX; Schema: landing; Owner: -
--

CREATE INDEX ix_landing_inst_tribal ON landing.institutions USING btree (is_tribal) WHERE is_tribal;


--
-- Name: ix_landing_inst_uei; Type: INDEX; Schema: landing; Owner: -
--

CREATE INDEX ix_landing_inst_uei ON landing.institutions USING btree (ueis);


--
-- Name: ix_lp_inst; Type: INDEX; Schema: landing; Owner: -
--

CREATE INDEX ix_lp_inst ON landing.learned_patterns USING btree (unitid, source_type);


--
-- Name: ix_mv_inst_carn; Type: INDEX; Schema: landing; Owner: -
--

CREATE INDEX ix_mv_inst_carn ON landing.mv_institution_page USING btree (carnegie_basic_slug);


--
-- Name: ix_mv_inst_page; Type: INDEX; Schema: landing; Owner: -
--

CREATE UNIQUE INDEX ix_mv_inst_page ON landing.mv_institution_page USING btree (unitid);


--
-- Name: ix_mv_inst_slug; Type: INDEX; Schema: landing; Owner: -
--

CREATE INDEX ix_mv_inst_slug ON landing.mv_institution_page USING btree (slug);


--
-- Name: ix_mv_inst_state; Type: INDEX; Schema: landing; Owner: -
--

CREATE INDEX ix_mv_inst_state ON landing.mv_institution_page USING btree (state_slug);


--
-- Name: ix_mv_research_summary; Type: INDEX; Schema: landing; Owner: -
--

CREATE UNIQUE INDEX ix_mv_research_summary ON landing.mv_research_funding_summary USING btree (unitid);


--
-- Name: ix_peers_lookup; Type: INDEX; Schema: landing; Owner: -
--

CREATE INDEX ix_peers_lookup ON landing.peer_groups USING btree (unitid, algorithm, algorithm_version, rank);


--
-- Name: ix_raw_dedupe; Type: INDEX; Schema: landing; Owner: -
--

CREATE INDEX ix_raw_dedupe ON landing.raw_payloads USING btree (unitid, source_type, body_sha256);


--
-- Name: ix_raw_latest; Type: INDEX; Schema: landing; Owner: -
--

CREATE INDEX ix_raw_latest ON landing.raw_payloads USING btree (unitid, source_type, fetched_at DESC);


--
-- Name: ix_research_awards_agency; Type: INDEX; Schema: landing; Owner: -
--

CREATE INDEX ix_research_awards_agency ON landing.research_awards USING btree (unitid, agency, fiscal_year DESC);


--
-- Name: ix_research_awards_inst; Type: INDEX; Schema: landing; Owner: -
--

CREATE INDEX ix_research_awards_inst ON landing.research_awards USING btree (unitid, fiscal_year DESC);


--
-- Name: ix_research_awards_pi; Type: INDEX; Schema: landing; Owner: -
--

CREATE INDEX ix_research_awards_pi ON landing.research_awards USING btree (pi_name);


--
-- Name: ix_runs_inst; Type: INDEX; Schema: landing; Owner: -
--

CREATE INDEX ix_runs_inst ON landing.scraper_runs USING btree (unitid, source_type, started_at DESC);


--
-- Name: ix_runs_status; Type: INDEX; Schema: landing; Owner: -
--

CREATE INDEX ix_runs_status ON landing.scraper_runs USING btree (status, started_at DESC);


--
-- Name: ix_sitemaps_inst; Type: INDEX; Schema: landing; Owner: -
--

CREATE INDEX ix_sitemaps_inst ON landing.sitemaps USING btree (unitid);


--
-- Name: ix_smentry_class; Type: INDEX; Schema: landing; Owner: -
--

CREATE INDEX ix_smentry_class ON landing.sitemap_entries USING btree (classified_as) WHERE (classified_as IS NOT NULL);


--
-- Name: ix_smentry_inst; Type: INDEX; Schema: landing; Owner: -
--

CREATE INDEX ix_smentry_inst ON landing.sitemap_entries USING btree (unitid);


--
-- Name: brand_assets brand_assets_raw_payload_id_fkey; Type: FK CONSTRAINT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.brand_assets
    ADD CONSTRAINT brand_assets_raw_payload_id_fkey FOREIGN KEY (raw_payload_id) REFERENCES landing.raw_payloads(id);


--
-- Name: brand_assets brand_assets_unitid_fkey; Type: FK CONSTRAINT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.brand_assets
    ADD CONSTRAINT brand_assets_unitid_fkey FOREIGN KEY (unitid) REFERENCES landing.institutions(unitid);


--
-- Name: canonical_urls canonical_urls_source_type_fkey; Type: FK CONSTRAINT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.canonical_urls
    ADD CONSTRAINT canonical_urls_source_type_fkey FOREIGN KEY (source_type) REFERENCES landing.source_types(source_type);


--
-- Name: canonical_urls canonical_urls_unitid_fkey; Type: FK CONSTRAINT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.canonical_urls
    ADD CONSTRAINT canonical_urls_unitid_fkey FOREIGN KEY (unitid) REFERENCES landing.institutions(unitid);


--
-- Name: cds_links cds_links_raw_payload_id_fkey; Type: FK CONSTRAINT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.cds_links
    ADD CONSTRAINT cds_links_raw_payload_id_fkey FOREIGN KEY (raw_payload_id) REFERENCES landing.raw_payloads(id);


--
-- Name: cds_links cds_links_unitid_fkey; Type: FK CONSTRAINT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.cds_links
    ADD CONSTRAINT cds_links_unitid_fkey FOREIGN KEY (unitid) REFERENCES landing.institutions(unitid);


--
-- Name: crawl_log crawl_log_source_type_fkey; Type: FK CONSTRAINT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.crawl_log
    ADD CONSTRAINT crawl_log_source_type_fkey FOREIGN KEY (source_type) REFERENCES landing.source_types(source_type);


--
-- Name: crawl_log crawl_log_unitid_fkey; Type: FK CONSTRAINT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.crawl_log
    ADD CONSTRAINT crawl_log_unitid_fkey FOREIGN KEY (unitid) REFERENCES landing.institutions(unitid);


--
-- Name: ir_contacts ir_contacts_raw_payload_id_fkey; Type: FK CONSTRAINT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.ir_contacts
    ADD CONSTRAINT ir_contacts_raw_payload_id_fkey FOREIGN KEY (raw_payload_id) REFERENCES landing.raw_payloads(id);


--
-- Name: ir_contacts ir_contacts_unitid_fkey; Type: FK CONSTRAINT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.ir_contacts
    ADD CONSTRAINT ir_contacts_unitid_fkey FOREIGN KEY (unitid) REFERENCES landing.institutions(unitid);


--
-- Name: ir_documents ir_documents_raw_payload_id_fkey; Type: FK CONSTRAINT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.ir_documents
    ADD CONSTRAINT ir_documents_raw_payload_id_fkey FOREIGN KEY (raw_payload_id) REFERENCES landing.raw_payloads(id);


--
-- Name: ir_documents ir_documents_unitid_fkey; Type: FK CONSTRAINT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.ir_documents
    ADD CONSTRAINT ir_documents_unitid_fkey FOREIGN KEY (unitid) REFERENCES landing.institutions(unitid);


--
-- Name: ir_pages ir_pages_raw_payload_id_fkey; Type: FK CONSTRAINT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.ir_pages
    ADD CONSTRAINT ir_pages_raw_payload_id_fkey FOREIGN KEY (raw_payload_id) REFERENCES landing.raw_payloads(id);


--
-- Name: ir_pages ir_pages_unitid_fkey; Type: FK CONSTRAINT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.ir_pages
    ADD CONSTRAINT ir_pages_unitid_fkey FOREIGN KEY (unitid) REFERENCES landing.institutions(unitid);


--
-- Name: job_postings job_postings_raw_payload_id_fkey; Type: FK CONSTRAINT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.job_postings
    ADD CONSTRAINT job_postings_raw_payload_id_fkey FOREIGN KEY (raw_payload_id) REFERENCES landing.raw_payloads(id);


--
-- Name: job_postings job_postings_unitid_fkey; Type: FK CONSTRAINT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.job_postings
    ADD CONSTRAINT job_postings_unitid_fkey FOREIGN KEY (unitid) REFERENCES landing.institutions(unitid);


--
-- Name: learned_patterns learned_patterns_source_type_fkey; Type: FK CONSTRAINT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.learned_patterns
    ADD CONSTRAINT learned_patterns_source_type_fkey FOREIGN KEY (source_type) REFERENCES landing.source_types(source_type);


--
-- Name: learned_patterns learned_patterns_unitid_fkey; Type: FK CONSTRAINT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.learned_patterns
    ADD CONSTRAINT learned_patterns_unitid_fkey FOREIGN KEY (unitid) REFERENCES landing.institutions(unitid);


--
-- Name: notable_alumni notable_alumni_raw_payload_id_fkey; Type: FK CONSTRAINT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.notable_alumni
    ADD CONSTRAINT notable_alumni_raw_payload_id_fkey FOREIGN KEY (raw_payload_id) REFERENCES landing.raw_payloads(id);


--
-- Name: notable_alumni notable_alumni_unitid_fkey; Type: FK CONSTRAINT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.notable_alumni
    ADD CONSTRAINT notable_alumni_unitid_fkey FOREIGN KEY (unitid) REFERENCES landing.institutions(unitid);


--
-- Name: peer_groups peer_groups_peer_unitid_fkey; Type: FK CONSTRAINT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.peer_groups
    ADD CONSTRAINT peer_groups_peer_unitid_fkey FOREIGN KEY (peer_unitid) REFERENCES landing.institutions(unitid);


--
-- Name: peer_groups peer_groups_unitid_fkey; Type: FK CONSTRAINT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.peer_groups
    ADD CONSTRAINT peer_groups_unitid_fkey FOREIGN KEY (unitid) REFERENCES landing.institutions(unitid);


--
-- Name: raw_payloads raw_payloads_source_type_fkey; Type: FK CONSTRAINT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.raw_payloads
    ADD CONSTRAINT raw_payloads_source_type_fkey FOREIGN KEY (source_type) REFERENCES landing.source_types(source_type);


--
-- Name: raw_payloads raw_payloads_unitid_fkey; Type: FK CONSTRAINT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.raw_payloads
    ADD CONSTRAINT raw_payloads_unitid_fkey FOREIGN KEY (unitid) REFERENCES landing.institutions(unitid);


--
-- Name: research_awards research_awards_raw_payload_id_fkey; Type: FK CONSTRAINT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.research_awards
    ADD CONSTRAINT research_awards_raw_payload_id_fkey FOREIGN KEY (raw_payload_id) REFERENCES landing.raw_payloads(id);


--
-- Name: research_awards research_awards_unitid_fkey; Type: FK CONSTRAINT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.research_awards
    ADD CONSTRAINT research_awards_unitid_fkey FOREIGN KEY (unitid) REFERENCES landing.institutions(unitid);


--
-- Name: research_expenditures research_expenditures_raw_payload_id_fkey; Type: FK CONSTRAINT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.research_expenditures
    ADD CONSTRAINT research_expenditures_raw_payload_id_fkey FOREIGN KEY (raw_payload_id) REFERENCES landing.raw_payloads(id);


--
-- Name: research_expenditures research_expenditures_unitid_fkey; Type: FK CONSTRAINT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.research_expenditures
    ADD CONSTRAINT research_expenditures_unitid_fkey FOREIGN KEY (unitid) REFERENCES landing.institutions(unitid);


--
-- Name: scraper_runs scraper_runs_source_type_fkey; Type: FK CONSTRAINT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.scraper_runs
    ADD CONSTRAINT scraper_runs_source_type_fkey FOREIGN KEY (source_type) REFERENCES landing.source_types(source_type);


--
-- Name: scraper_runs scraper_runs_unitid_fkey; Type: FK CONSTRAINT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.scraper_runs
    ADD CONSTRAINT scraper_runs_unitid_fkey FOREIGN KEY (unitid) REFERENCES landing.institutions(unitid);


--
-- Name: sitemap_entries sitemap_entries_classified_as_fkey; Type: FK CONSTRAINT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.sitemap_entries
    ADD CONSTRAINT sitemap_entries_classified_as_fkey FOREIGN KEY (classified_as) REFERENCES landing.source_types(source_type);


--
-- Name: sitemap_entries sitemap_entries_sitemap_id_fkey; Type: FK CONSTRAINT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.sitemap_entries
    ADD CONSTRAINT sitemap_entries_sitemap_id_fkey FOREIGN KEY (sitemap_id) REFERENCES landing.sitemaps(id) ON DELETE CASCADE;


--
-- Name: sitemap_entries sitemap_entries_unitid_fkey; Type: FK CONSTRAINT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.sitemap_entries
    ADD CONSTRAINT sitemap_entries_unitid_fkey FOREIGN KEY (unitid) REFERENCES landing.institutions(unitid);


--
-- Name: sitemaps sitemaps_unitid_fkey; Type: FK CONSTRAINT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.sitemaps
    ADD CONSTRAINT sitemaps_unitid_fkey FOREIGN KEY (unitid) REFERENCES landing.institutions(unitid);


--
-- Name: wiki_summaries wiki_summaries_raw_payload_id_fkey; Type: FK CONSTRAINT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.wiki_summaries
    ADD CONSTRAINT wiki_summaries_raw_payload_id_fkey FOREIGN KEY (raw_payload_id) REFERENCES landing.raw_payloads(id);


--
-- Name: wiki_summaries wiki_summaries_unitid_fkey; Type: FK CONSTRAINT; Schema: landing; Owner: -
--

ALTER TABLE ONLY landing.wiki_summaries
    ADD CONSTRAINT wiki_summaries_unitid_fkey FOREIGN KEY (unitid) REFERENCES landing.institutions(unitid);


--
-- PostgreSQL database dump complete
--

\unrestrict gU840wfQbXG31Qpp5Jxx2A4po1wPEuNqGnIbRdqTajclMDinnCFNIjrG4KIKEU3

